# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-14 20:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20180111_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighborImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='主题')),
                ('imgUrl', models.ImageField(upload_to='banner', verbose_name='图片')),
                ('index', models.IntegerField(default=0, verbose_name='顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '推荐图',
                'verbose_name_plural': '推荐图',
            },
        ),
    ]
