# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-11 21:42
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgUrl', models.ImageField(upload_to='banner', verbose_name='轮播图片')),
                ('index', models.IntegerField(default=0, verbose_name='轮播顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播商品',
                'verbose_name_plural': '轮播商品',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate', models.CharField(default='', max_length=20, verbose_name='促销类别')),
                ('desc', models.CharField(default='', max_length=20, verbose_name='促销详情')),
                ('show', models.BooleanField(default=True, verbose_name='是否展示')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '促销信息',
                'verbose_name_plural': '促销信息',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='商品名')),
                ('sold_num', models.IntegerField(default=0, verbose_name='商品销售量')),
                ('fav', models.FloatField(default='', max_length=30, verbose_name='好评率')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('goods_num', models.IntegerField(default=0, verbose_name='库存数')),
                ('shop_price', models.FloatField(default=0, verbose_name='本店价格')),
                ('desc', models.TextField(max_length=500, verbose_name='商品简短描述')),
                ('img', models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='封面图')),
                ('isDiscount', models.BooleanField(default=False, verbose_name='是否折扣')),
                ('discount', models.IntegerField(default=10, verbose_name='打几折')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否新品')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热销')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code')),
                ('desc', models.TextField(default='', help_text='类别描述', verbose_name='类别描述')),
                ('is_tab', models.BooleanField(default=False, help_text='是否导航', verbose_name='是否导航')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
            },
        ),
        migrations.CreateModel(
            name='HotSearchWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotSearch', models.CharField(default='', max_length=20, verbose_name='热搜词')),
                ('index', models.IntegerField(default=0, verbose_name='排序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '热搜词',
                'verbose_name_plural': '热搜词',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='商家名', max_length=30, verbose_name='商家名')),
                ('infomation', models.TextField(default='', help_text='商家描述', max_length=200, verbose_name='商家简单描述')),
                ('logo', models.ImageField(max_length=200, upload_to='stores/')),
                ('phone', models.CharField(max_length=11, verbose_name='商家电话')),
                ('openingHours', models.CharField(default='09:00-22:50', max_length=100, verbose_name='营业时间')),
                ('notice', models.TextField(default='欢迎光临', max_length=200, verbose_name='商家公告信息')),
                ('pics', DjangoUeditor.models.UEditorField(default='', verbose_name='商家实景图片')),
                ('startAmount', models.IntegerField(default=15, verbose_name='起送价')),
                ('trans', models.IntegerField(default=5, verbose_name='配送费')),
                ('orders', models.IntegerField(default=0, verbose_name='月订单量')),
                ('favComments', models.FloatField(default='', max_length=30, verbose_name='好评率')),
                ('address', models.CharField(default='', max_length=100, verbose_name='商家地址')),
                ('praise', models.BooleanField(default=False, verbose_name='口碑')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商家',
                'verbose_name_plural': '商家',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类别'),
        ),
        migrations.AddField(
            model_name='goods',
            name='store',
            field=models.ManyToManyField(to='goods.Store', verbose_name='商家'),
        ),
        migrations.AddField(
            model_name='discount',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discountList', to='goods.Store', verbose_name='商家'),
        ),
        migrations.AddField(
            model_name='banner',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='goods.Store', verbose_name='商家'),
        ),
    ]
