# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-13 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180113_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialindex',
            name='imgUrl',
            field=models.ImageField(upload_to='banner', verbose_name='广告图片'),
        ),
        migrations.AlterField(
            model_name='specialindex',
            name='index',
            field=models.IntegerField(default=0, verbose_name='广告顺序'),
        ),
    ]
