# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-14 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180113_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='store',
            field=models.ManyToManyField(related_name='good', to='goods.Store', verbose_name='商家'),
        ),
    ]
