# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-14 20:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20180114_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgUrl', models.ImageField(upload_to='banner', verbose_name='图片')),
                ('index', models.IntegerField(default=0, verbose_name='顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_detail', to='goods.Store', verbose_name='商家')),
            ],
            options={
                'verbose_name': '商家实景图片',
                'verbose_name_plural': '商家实景图片',
            },
        ),
    ]
