# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-15 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20180115_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='desc',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='商品简短描述'),
        ),
    ]
