# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-15 20:13
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20180115_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='pics',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='商家实景图片'),
        ),
    ]
