# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-11 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgUrl', models.ImageField(upload_to='find', verbose_name='发现图片')),
                ('title', models.CharField(max_length=100, verbose_name='发现名')),
                ('desc', models.TextField(max_length=500, verbose_name='发现描述')),
            ],
            options={
                'verbose_name': '发现页',
                'verbose_name_plural': '发现页',
            },
        ),
    ]
