# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-13 17:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgsFinds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='主题')),
                ('imgUrl', models.ImageField(upload_to='banner', verbose_name='活动图片')),
                ('index', models.IntegerField(default=0, verbose_name='活动顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '活动图',
                'verbose_name_plural': '活动图',
            },
        ),
    ]
