# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-16 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='verifycode',
            name='imgCode',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hasPassword',
            field=models.BooleanField(default=False, verbose_name='密码是否设置了'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='headImg',
            field=models.ImageField(default='head\\toxiang.jpg', upload_to='head/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default=1, max_length=30, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
