# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-16 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20180115_2013'),
        ('user_operation', '0002_auto_20180111_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleavingmessage',
            name='store',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='goods.Store', verbose_name='商家'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='signer_sex',
            field=models.CharField(default='先生', max_length=20, verbose_name='签收人性别'),
        ),
    ]
